version: '3.8'
services:
  jupyterlab_ai:
    image: devijlab
    build:
      context: .
    volumes:
      - /home/jupyterlab_docker/datasets:/datasets:ro
      - /home/jupyterlab_docker/notebooks:/opt/app/data
    ports:
      - 8889:8888
    networks:
      - devijlab-net
    entrypoint: ["jupyter", "lab"]
    command: ["--ip=0.0.0.0", "--port=8888", "--notebook-dir=/opt/app/data", "--allow-root"]
    environment:
      - JUPYTER_ENABLE_LAB=yes
volumes:
  devijlab-vault:
networks:
  devijlab-net:
